// <auto-generated />
namespace Live_Demo_Alpha.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserBlogPostsrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserBlogPostsrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011414394_User-BlogPosts relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
